---
- name: Run LCM Inventory
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/operations/$actions/performInventory"
    method: POST
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 202
    return_content: true
  register: role_nutanix_prism_lcm_inventory_result
  ignore_errors: false

- name: Debug role_nutanix_prism_lcm_inventory_result.json
  debug:
    var: role_nutanix_prism_lcm_inventory_result.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Store LCM inventory task uuid
  set_fact:
    role_nutanix_prism_lcm_inventory_task_uuid: "{{ role_nutanix_prism_lcm_inventory_result.json.data.extId }}"

- name: Debug role_nutanix_prism_lcm_initial_inventory_task_uuid
  debug:
    var: role_nutanix_prism_lcm_inventory_task_uuid
  when:
    - role_nutanix_prism_lcm_debug

- name: Wait for LCM inventory task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_prism_lcm_host }}"
    role_nutanix_prism_monitor_task_host_username: "{{ role_nutanix_prism_lcm_host_username }}"
    role_nutanix_prism_monitor_task_host_password: "{{ role_nutanix_prism_lcm_host_password }}"
    role_nutanix_prism_monitor_task_host_port: "{{ role_nutanix_prism_lcm_host_port | default(omit) }}"
    role_nutanix_prism_monitor_task_host_validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs | default(omit) }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_prism_lcm_debug | default(omit) }}"
    role_nutanix_prism_monitor_task_uuid: "{{ role_nutanix_prism_lcm_inventory_task_uuid }}"

- name: Set role_nutanix_prism_lcm_inventory_task_status
  set_fact:
    role_nutanix_prism_lcm_inventory_task_status: "{{ role_nutanix_prism_monitor_task_result }}"

- name: Debug role_nutanix_prism_lcm_inventory_task_status
  debug:
    var: role_nutanix_prism_lcm_inventory_task_status
  when:
    - role_nutanix_prism_lcm_debug
