---
- name: LCM update pre-check
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/operations/$actions/performPrecheck"
    method: POST
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    body_format: json
    body:
      entityUpdateSpecs: "{{ role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_prism_lcm_update_precheck_task
  ignore_errors: false

- name: Debug role_nutanix_prism_lcm_update_precheck_task.json
  debug:
    var: role_nutanix_prism_lcm_update_precheck_task.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Checking LCM pre-check task status
  uri:
    url:
      "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/resources/tasks\
      /{{ role_nutanix_prism_lcm_update_precheck_task.json.data.extId }}"
    method: GET
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_prism_lcm_update_precheck_task_debug

- name: Debug role_nutanix_prism_lcm_update_precheck_task_debug.json
  debug:
    var: role_nutanix_prism_lcm_update_precheck_task_debug.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Wait for LCM update pre-check task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_prism_lcm_host }}"
    role_nutanix_prism_monitor_task_username: "{{ role_nutanix_prism_lcm_host_username }}"
    role_nutanix_prism_monitor_task_password: "{{ role_nutanix_prism_lcm_host_password }}"
    role_nutanix_prism_monitor_task_port: "{{ role_nutanix_prism_lcm_host_port | default(omit) }}"
    role_nutanix_prism_monitor_task_validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs | default(omit) }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_prism_lcm_debug | default(omit) }}"
    role_nutanix_prism_monitor_task_uuid: "{{ role_nutanix_prism_lcm_update_precheck_task.json.data.extId }}"
    role_nutanix_prism_monitor_task_retries: 30
    role_nutanix_prism_monitor_task_retry_delay: 30

- name: Set nutanix_lcm_update_precheck_task
  set_fact:
    nutanix_lcm_update_precheck_task: "{{ role_nutanix_prism_monitor_task_result }}"

- name: Debug nutanix_lcm_update_precheck_task
  debug:
    var: nutanix_lcm_update_precheck_task
  when:
    - nutanix_lcm_update_precheck_task
