---
- name: Get LCM update recommendations for firmware
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/resources/recommendations"
    method: POST
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    body_format: json
    body:
      entityTypes: ["firmware"]
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_prism_lcm_update_recommendations
  ignore_errors: false

- name: Debug role_nutanix_prism_lcm_update_recommendations.json
  ansible.builtin.debug:
    var: role_nutanix_prism_lcm_update_recommendations.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Generate firmware update plan
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/resources/plan"
    method: POST
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    body_format: json
    body: "{{ role_nutanix_prism_lcm_update_recommendations.json.data.entity_update_spec_list }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64sm_api_auth_string_b64 }}"
    status_code:
      - 200
      - 201
    return_content: true
  register: role_nutanix_prism_lcm_update_plan
  ignore_errors: false
  when:
    - role_nutanix_prism_lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

- name: Debug role_nutanix_prism_lcm_update_plan.json
  ansible.builtin.debug:
    var: role_nutanix_prism_lcm_update_plan.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Anticipated LCM actions during firmware upgrade
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_lcm_update_plan.json.data.hostplan_list | default([]) | json_query('[].action') | unique | list }}"
  when:
    - role_nutanix_prism_lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

- name: Run LCM firmware update pre-checks
  ansible.builtin.import_tasks: lcm_precheck.yml
  when:
    - role_nutanix_prism_lcm_run_precheck
    - role_nutanix_prism_lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

- name: Update progress check delay for firmware updates
  ansible.builtin.set_fact:
    role_nutanix_prism_lcm_delay: 3600

- name: Run LCM firmware update
  ansible.builtin.import_tasks: lcm_update.yml
  when:
    - role_nutanix_prism_lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0
