---
- name: Set LCM update list to specific software
  set_fact:
    role_nutanix_prism_lcm_sw_update_list: "{{ role_nutanix_prism_lcm_sw_update_list | default([]) + [item] }}"
  loop: "{{ role_nutanix_prism_lcm_sw_target_entity_list }}"
  when:
    - role_nutanix_prism_lcm_sw_to_update is defined
    - item.entityModel in role_nutanix_prism_lcm_sw_to_update | default([])

- name: Debug role_nutanix_prism_lcm_sw_update_list
  debug:
    var: role_nutanix_prism_lcm_sw_update_list
  when:
    - role_nutanix_prism_lcm_debug

- name: Debug update recommendations POST body
  debug:
    msg: "{{ lookup('template', 'lcm-req.j2') | from_yaml | to_json }}"
  when:
    - role_nutanix_prism_lcm_debug

- name: Get LCM software update recommendations
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/resources/recommendations"
    method: POST
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    body_format: json
    body: "{{ lookup('template', 'lcm-req.j2') | from_yaml | to_json }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_prism_lcm_update_recommendations
  ignore_errors: false

- name: Debug role_nutanix_prism_lcm_update_recommendations.json
  debug:
    var: role_nutanix_prism_lcm_update_recommendations.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Debug role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs
  debug:
    msg: "{{ role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs }}"
  when:
    - role_nutanix_prism_lcm_debug

- name: Generate software update plan
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/lcm/v4.0.a1/resources/plan"
    method: POST
    validate_certs: "{{ role_nutanix_prism_lcm_host_validate_certs }}"
    body_format: json
    body:
      entityUpdateSpecs: "{{ role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_prism_lcm_update_plan
  ignore_errors: false
  when:
    - role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs | default([]) | length > 0

- name: Debug role_nutanix_prism_lcm_update_plan
  debug:
    var: role_nutanix_prism_lcm_update_plan.json
  when:
    - role_nutanix_prism_lcm_debug

- name: Anticipated LCM actions during software upgrade
  debug:
    msg: >-
      "{{ role_nutanix_prism_lcm_update_plan.json.data.hostUpgradePlans | default ([])
      | json_query('[].action') | unique | list }}"
  when:
    - role_nutanix_prism_lcm_update_plan.json.data.hostUpgradePlans | default([]) | length > 0

- name: Run LCM software update pre-checks
  import_tasks: lcm_precheck.yml
  when:
    - role_nutanix_prism_lcm_run_precheck
    - role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs | default([]) | length > 0

- name: Run LCM software update
  import_tasks: lcm_update.yml
  when: role_nutanix_prism_lcm_update_recommendations.json.data.entityUpdateSpecs | default([]) | length > 0
